#!/usr/bin/env bash

# Check if there are enough arguments
if [ $# -lt 2 ]; then
  echo "Usage: $0 <source_files> <executable_name>"
  exit 1
fi

# Extract the last argument as the executable name
exe_name="${@: -1}"
# Extract all but the last argument as source files
source_files="${@:1:$(($# - 1))}"

# Function to compile, run, and optionally delete the executable
compile_and_run()
{
  local compiler="$1"
  local flags="$2"
  local files="$3"
  local exe_name="$4"

  echo "Compiling $files..."
  $compiler $flags $files -o "$exe_name"

  # Check if the compilation was successful
  if [ $? -eq 0 ]; then
    echo "Running $exe_name..."
    echo "----------------------------------------------"
    ./"$exe_name"

    # Ask user if they want to delete the executable
    echo "----------------------------------------------"
    read -p "Execution of '$exe_name' has finished.Do you want to delete the executable '$exe_name'? (y/n): " confirm
    if [[ $confirm == [yY] ]]; then
      rm -f "$exe_name"
      echo "'$exe_name' has been deleted."
    else
      echo "'$exe_name' has not been deleted."
    fi

    # Print a message indicating that the execution has finished
    echo "Execution of '$exe_name' has finished."
  else
    echo "Compilation failed."
    exit 1
  fi
}

# Determine the file extension of the first source file
first_file="$1"
extension="${first_file##*.}"

# Define compilation flags for C and C++
c_flags="-lm -Wall -Wextra -Wpedantic -Wnull-dereference -Wcast-align -Wparentheses -Walloc-zero -Wcast-qual -Wconversion -Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wformat-signedness -Winit-self -Wlogical-op -Wmissing-declarations -Wshadow -Wswitch-default -Wswitch-enum -Wundef -Wunused-macros -Wwrite-strings -Wsign-conversion -Og -g3 -std=c23 -fsanitize=address,undefined"
cpp_flags="-lpthread -Wall -Wextra -Wpedantic -Wnull-dereference -Wmissing-noreturn -Wcast-align -Wparentheses -Walloc-zero -Wcast-qual -Wconversion -Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wformat-signedness -Winit-self -Wlogical-op -Wmissing-declarations -Wshadow -Wswitch-default -Wswitch-enum -Wundef -Wunused-macros -Wwrite-strings -Wnon-virtual-dtor -Wzero-as-null-pointer-constant -Wsign-conversion -Wsuggest-override -Og -g3 -std=c++23 -fsanitize=address,undefined"

case "$extension" in
  c)
    compile_and_run "gcc" "$c_flags" "$source_files" "$exe_name"
    ;;
  cpp | cxx | cc)
    compile_and_run "g++" "$cpp_flags" "$source_files" "$exe_name"
    ;;
  *)
    echo "Unsupported file type: $extension"
    exit 1
    ;;
esac
