#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  echo "Usage: $0 <file_or_directory>"
  exit 1
fi

input_path="$1"

if [ -d "$input_path" ]; then
  if [ -f "$input_path/CMakeLists.txt" ]; then # 输入是目录
    echo "CMake project detected. Configuring, building, and running..."
    cmake -B"$input_path/build" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON &&
      cmake --build "$input_path/build" &&
      echo "===== output =====" &&
      "$input_path/build/$(grep add_executable "$input_path/CMakeLists.txt" | sed "s/\s*add_executable\s*(\s*//g" | cut -d " " -f 1)"
  else
    echo "No CMakeLists.txt found in the directory."
    exit 1
  fi
else
  extension="${input_path##*.}" # 输入是文件，删除最后一个.及其之前的所有内容
  case "$extension" in
    c)
      exe_name=$(basename "${filename%.*}")
      echo "Compiling and running C file..."
      gcc "$filename" -o "${exe_name}" -Wall -Wextra -Wpedantic -Wparentheses -Walloc-zero -Wcast-qual -Wconversion -Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wformat-signedness -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-prototypes -Wshadow -Wswitch-default -Wswitch-enum -Wundef -Wunused-macros -Wwrite-strings -Wsign-conversion -Og -g3 -std=c23 -fsanitize=address,undefined && ./"${exe_name}" && rm -rf "$exe_name"
      ;;
    cpp | cxx | cc)
      exe_name=$(basename "${filename%.*}")
      echo "Compiling and running C++ file..."
      g++ "$filename" -o "$exe_name" -Wall -Wextra -Wpedantic -Wparentheses -Walloc-zero -Wcast-qual -Wconversion -Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wformat-signedness -Winit-self -Wlogical-op -Wmissing-declarations -Wshadow -Wswitch-default -Wswitch-enum -Wundef -Wunused-macros -Wwrite-strings -Wnon-virtual-dtor -Wzero-as-null-pointer-constant -Wsign-conversion -Wsuggest-override -Og -g3 -std=c++23 -fsanitize=address,undefined && ./"$exe_name" && rm -rf "$exe_name"
      ;;
    py)
      echo "Running Python file..."
      python3 "$filename"
      ;;
    js)
      echo "Running JavaScript file..."
      node "$filename"
      ;;
    *)
      echo "Unsupported file type: $extension"
      exit 1
      ;;
  esac
fi
