#!/usr/bin/env bash

echo -e '\033[38;2;102;153;204;1m'

cat << EOF
find在指定目录树下递归查找文件或目录。

基本格式:
find [路径...] [匹配条件...] [动作表达式]

常用参数:
-name [文件名] 查找与文件名匹配的文件。
-iname [文件名] 查找与文件名匹配的文件，忽略大小写。
-type [类型] 查找特定类型的文件，例如 f 表示普通文件, d 表示目录。
-size [大小] 查找特定大小的文件，例如 10M/-10M/+10M分别表示查找等于/小于/大于10MB的文件。
-perm [权限] 查找具有特定权限的文件，例如 644。
-user [用户名] 查找属于特定用户的文件。
-group [组名] 查找属于特定组的文件。
-mtime [天数] 查找在指定天数内被修改过的文件。
-atime [天数] 查找在指定天数内被访问过的文件。
-ctime [天数] 查找在指定天数内被改变状态的文件。
-exec [命令] {} \\; 对匹配的文件执行指定的命令。{}用来保存搜索到的文件，\\用来转义;
-execdir [命令] {} \\; 在匹配文件所在的目录中执行指定的命令。
-delete 删除匹配的文件。
-maxdepth [层级] 限制查找的目录深度。
-mindepth [层级] 指定最小的查找目录深度。
-empty 查找空文件或目录。
-newer [文件] 查找比指定文件更新的文件。
-not [表达式] 查找不匹配表达式的文件。
-or 结合两个表达式，匹配任意一个表达式的文件。

示例用法:
查找当前目录及子目录下所有 '.txt' 文件，忽略大小写:
find . -iname '*.txt'

查找当前目录及子目录下大于100M小于200M的文件:
find . -size +100M -size -200M

查找 /home 目录下所有属于用户 'alice' 的文件:
find /home -user alice

查找当前目录及子目录下最近7天内被修改过的 '.jpg' 文件:
find . -type f -name '*.jpg' -mtime -7

查找当前目录及子目录下所有空的子目录并删除它们:
find . -type d -empty -delete

查找当前目录及子目录下所有 '.sh' 文件并对每个文件执行 'chmod +x':
find . -type f -name '*.sh' -print -exec chmod +x {} \;
其中{} 是文件名的占位符，将被实际找到的文件名所替换;反斜杠用于转义分号, 分号是命令的终止符

查找当前目录及子目录下所有 备份文件, 并删除它们:
find . -name '*.bak' -type f -print -exec rm {} \;

递归地统计etc目录下含'telnet'文本的文件数目:
find /etc -type f -exec grep -il 'telnet' {} \; | wc -l

递归地打印当前目录下文件名以A(a)开头或结束的文件:
find . \\( -name '[Aa]*' -o -name '*[Aa]' \)

删除当前目录下所有非PDF文件:
find . -type f ! -name '*.pdf' -exec rm -v {} \;
EOF

echo -e '\033[0m'
