#!/usr/bin/env bash

echo -e '\033[38;2;102;153;204;1m'

cat << EOF
GCC（GNU Compiler Collection）是按照模块化设计的，由前端、优化器、后端组成。
前端用于解析特定语言的语法，生成一种中间表示（IR）；
实现不同的前端后，GCC可以支持多种语言，如C、C++、Fortran、Go等
优化器对这种中间表示进行优化；
后端则负责将优化后的IR转换为目标平台的机器代码.
GCC能够进行跨平台交叉编译，例如，在x86架构的计算机上编译出ARM架构的程序。

gcc编译c/c++程序的四个阶段：
预处理(Preprocessing), 编译选项为-E, 生成.i (intermediate)文件
编译(Compilation), 编译选项为-S, 生成.s  (assembly)文件
汇编(Assembly), 编译选项为-c, 生成.o (object)文件
链接(Linking), 生成可执行文件

gcc -E -dM - < /dev/null 这个命令的作用是让 GCC 编译器预处理一个空的输入文件,并输出所有预定义的宏定义。
-dM: 这个选项告诉编译器输出所有预定义的宏定义,包括编译器自身定义的宏和系统定义的宏。
-: 这个连字符表示从标准输入读取源代码。

编译时定义宏:
 #include <iostream>
using namespace std;
int main(){    cout << STR1 << STR2 << endl;}
g++ -D STR1='"hello, "' -D STR2='"world!"' test.cpp -o test

调试选项:
-g3: 向输出添加了更多的调试信息。 -g 和 -g3类似于-O 和 -O3

优化选项：
-O0 : 减少编译时间，使调试产生预期的结果。这是默认的优化级别
-O / -O1: 减少代码大小和执行时间, 编译需要消耗更多时间和内存
-O2: 执行几乎所有支持的优化。进一步增加生成代码的性能，但也会增加编译时间、
-O3: 进一步优化
-Os: 启用所有-O2优化，但经常增加代码大小的优化除外
-Oz: 积极优化尺寸而不是速度, 其行为类似于-Os, 包括启用大多数-O2优化
-Ofast: 启用所有-O3优化，还会启用违反标准的优化
-Og: 优化调试体验。启用-O1优化，但那些可能干扰调试的标志除外.调试代码时，它是比-O0更好的选择，-O0可能会禁止编译器收集一些调试信息

建议开启的警告:
-Wall
-Wextra
-Wpedantic 有助于编写更加符合标准的、可移植的代码
-Wparentheses 警告可疑的括号使用

-Walloc-zero: malloc(0)、realloc(x, 0)
-Wcast-qual 警告const属性丢失
-Wconversion 警告可能更改值的隐式类型转换
-Wdouble-promotion 当float被隐式提升为double时警告。在游戏开发中这会影响性能
-Wduplicated-branches 警告重复的if分支
-Wduplicated-cond 警告if链g中重复的条件
-Wfloat-equal 警告直接的浮点数比较, 如 x == y  x == 3.14
-Wformat=2 更严格地检查printf scanf的格式化字符串与实际参数不匹配
-Wformat-signedness int x = -1; printf("%u", x);
-Winit-self   int i = i;
-Wlogical-op if (a < 0 && a < 0)
-Wmissing-declarations 定义全局函数而没有前向声明
-Wmissing-prototypes 要求完整的声明，int foo(int i); 而不是int foo();
-Wpadded 结构体成员没有特意对齐，编译器插入了填充字节
-Wshadow 变量名与其他变量重名，被隐藏
-Wswitch-default switch语句没有default分支
-Wswitch-enum enum有red, blue两项, 但switchg中只有red分支
-Wundef 在 #if 指令中计算未定义的标识符
-Wunused-macros
-Wwrite-strings  char *x = "foobar" 因为x未显式声明为 const, 触发警告

一个典型的g++命令行：g++ -Wall -std=c++20 source1.cpp source2.cpp -o program

多文件编译示例：
注意，编译时需要指定头文件目录，但是根据cpp文件就能编译出.o文件，不依赖头文件。
project
├── include
│   └── functions.h
├── main.c
└── src
    └── functions.c

gcc -c -I./include src/functions.c -o functions.o
gcc -c -I./include main.c -o main.o
gcc main.o functions.o -o project

静态库:
静态库通常以.a作为文件扩展名，并且遵循lib<name>.a的命名规则，其中<name>是库的名称。
静态库可以包含多个目标文件（.o文件），并且可以通过ar命令(archive,归档)来创建。
归档文件可以在文件管理器中打开，打开后可以看到所有目标文件。
首先，编译每个源文件以生成目标文件：
gcc -c file1.c -o file1.o
gcc -c file2.c -o file2.o
接下来，将这些目标文件打包成example静态库:
ar rcs libexample.a file1.o file2.o
其中rcs表示replace，create，index——如果文件已经存在于静态库中，则替换它；如果静态库不存在，则创建它；创建索引，加快链接时的速度
在链接时使用example静态库:
gcc main.o -L. -lexample -o program
其中-L.表示在当前目录下查找静态库

动态链接库:
动态库通常以.so作为文件扩展名，并且遵循lib<name>.so.<version>的命名规则，其中<name>是库的基本名称，<version>是库的版本号。
首先，编译每个源文件以生成位置无关的目标文件：
gcc -c -fPIC file1.c -o file1.o
gcc -c -fPIC file2.c -o file2.o
其中PIC表示position independent code ，即位置无关代码。
创建动态库:
gcc -shared file1.o file2.o -o libexample.so.1
在链接时使用example动态库:
gcc main.o -L. -lexample -o program

当动态库和静态库中都存在同名的库时，程序会优先使用动态库。
系统共享库放在 /lib，/usr/lib等目录下。
使用ldd 可执行文件名命令可以查看程序运行时所依赖的动态库，以及这些动态库的路径。
你可以静态链接动态库: g++ -static main.cpp -o static_executable

总的来说，动态链接允许程序共享动态链接库，减少内存占用，并且允许动态更新库文件。
静态链接则将所有依赖打包进可执行文件，使得程序更加独立和可移植。

EOF

echo -e '\033[0m'
