#!/usr/bin/env bash

echo -e '\033[38;2;102;153;204;1m'

cat << EOF
gdb (GNU symbolic debugger) 是通过linux下ptrace系统调用实现的调试器，支持远程调试。
被调试的可执行文件必须加上-g选项编译，否则会提示No debugging symbols found in executable file

调试可执行文件: gdb exe_file
调试进程: gdb attach pid (进程会暂停执行; 退出前需要detach)
调试core dump文件: gdb exe_file corefile (执行ulimit -c unlimited以允许生成core文件)

+------------------------+-------------------------------------------------------------+
| 命令                   | 描述                                                         |
+------------------------+-------------------------------------------------------------+
| 回车                   | 执行上一条命令                                               |
| shell command-string/!command-string | 在gdb中执行shell命令                         |

| break/b line           | 在当前文件的line行添加断点                                   |
| break/b file:line      | 在指定文件的line行添加断点                                   |
| break/b func           | 在函数入口处添加断点， 如break Class::func()   break overloaded_function(args) |
| break/b file func      | 在指定文件的指定函数入口处添加断点                           |
| break/b -/+ offset     | 在当前程序暂停位置的前/后 offset 行上添加断点                |
| break/b if cond        | 条件断点，如 break if i == 10   break func() if ptr == 0    |
| tbreak/tb              | 添加临时断点。断点触发后自动删除                             |

| info break/i b         | 列出所有的断点及其编号                                       |
| delete num             | 删除编号为num的断点                                          |
| enable num             | 启用编号为num的断点                                          |
| disable num            | 禁用编号为num的断点                                          |

| next/n                 | step over, 执行下一行,不会进入函数内部                       |
| step/s                 | step into, 执行下一行,会进入函数内部                         |
| return val             | 不管当前函数是否执行完，立刻返回，可以指定返回值             |
| finish                 | 执行完当前函数                                               |
| continue/c             | 运行到下一个断点处                                           |
| until line             | 运行到指定行后停下来                                         |
| jump/j line/*addr      | 跳转到指定行或地址后，继续执行。跳过的代码不会被执行         |

| backtrace/bt           | 查看当前的函数调用栈。栈中的元素称为帧。该命令会帧的编号     |
| frame/f num            | 切换到编号为num的帧                                          |

| print/p var            | 查看变量或寄存器的值，如 print i、print &i、print abs(i)+3  |
| print/p var=i          | 设置变量或寄存器的值, 如print obj.member = value             |
| print/p expr           | 查看表达式的值，如 print a+b+c                              |
| print/p func()         | 查看函数的执行结果，如 print strerror(errno)  print arr.resize($1 + 3), $1表示当前帧的第一个参数 |
| print/p this           | 查看this指针的值                                            |
| print/p *this          | 查看当前对象的值                                            |
| ptype val              | 查看变量类型                                                |

| watch expr/*ptr        | 设置观察点。一旦expr的值发生改变，就会暂停程序。如 watch global_var if global_var >= 2 |
| awatch rwatch          | access watch, read watch                                    |
| info watch             | 查看所有观察点                                              |
| delete watch num       | 删除指定编号的观察点                                        |

| info thread            | 显示所有线程的运行情况                                      |
| thread num             | 切换到指定编号的线程                                        |

| list/l                 | 显示源代码                                                  |
| list/l line            | 显示源代码                                                  |
| list/l file:line       | 显示源代码                                                  |
| list/l func            | 显示源代码                                                  |
| list/l file:func       | 显示源代码                                                  |
| list/l fromline,toline | 显示源代码                                                  |
| show listsize          | 查看 list 命令显示的代码行数                                |
| set listsize count     | 设置 list 命令显示的代码行数                                |

| disassemble/dis        | 查看汇编代码                                                |

| set logging file <filename> | 临时输出到文件                                         |
| set logging overwrite [on | off] | 设置日志覆盖模式                                  |
| set logging redirect [on | off] | 设置日志重定向模式                                 |
| set logging on         | 开启日志记录                                               |
| set logging off        | 关闭日志记录                                               |
| show logging           | 显示日志记录状态                                           |
| save breakpoints temp.gdb    source temp.gdb | 保存/加载断点                        |

| set follow-fork-mode child | 在多进程调试时追踪子进程                                |
| set follow-fork-mode parent | 在多进程调试时追踪父进程 (默认)                        |

| set args               | 设置程序的命令行参数                                        |
| show args              | 查看程序的命令行参数                                        |
| run/r arg1 arg2 ...    | 运行程序，会执行到第一个断点处。可以传递程序的命令行参数    |
| start arg1 arg2 ...    | 准备执行main函数。可以传递程序的命令行参数                  |
| quit/q                 | 退出GDB                                                     |
EOF

echo -e '\033[0m'
