#!/usr/bin/env bash

echo -e '\033[38;2;102;153;204;1m'

cat << EOF
man和less等命令,在浏览文件内容时,有以下快捷键:
/pattern - 搜索pattern
n - 查找下一个匹配项
N - 查找上一个匹配项
g - 移动到文件头
G - 移动到文件尾
b / Page UP 向上翻滚一页
space / Page Down 向下翻滚一页
回车 向下滚动一行
EOF

echo -e '\033[0m'
