#!/usr/bin/env bash

echo -e '\033[38;2;102;153;204;1m'

cat << 'EOF'
## 内存监控
pmap: 显示进程的内存映射
vmstat: 报告虚拟内存统计信息

## 网络监控
ip addr: 显示 IP 地址和网络接口
ss: 替代较旧的 netstat 命令 (socket statistics)
iftop: 按主机显示接口上的带宽使用情况

## 进程监控
lsof: 列出打开的文件 (list open files)
lsof | grep LISTEN: 列出打开的文件，过滤只显示监听端口

## I/O 监控
iotop: 监控进程的 I/O 使用情况

## 系统信息
curl ipinfo.io: 获取公共 IP 地址和位置信息

## 磁盘使用
df: 报告文件系统磁盘空间使用情况
du: 估算文件空间使用情况

dmidecode: 获取系统硬件信息

注意：运行大多数这些命令时需要使用 sudo 以获取完整信息。
EOF

echo -e '\033[0m'
