#!/usr/bin/env bash

echo -e '\033[38;2;102;153;204;1m'

cat << EOF
ps显示当前终端(模拟器)中的进程，包括后台进程组中的进程。

如果 ps 命令显示的进程名称被方括号 [] 包围，表示它是一个内核线程。

ps aux: BSD风格,显示cpu和内存使用率。
STAT列:
    D (Disk Sleep): 不可中断的睡眠状态,通常是在等待I/O操作完成。
    I (Idle): 空闲内核进程。
    R (Running): 进程正在运行或位于运行队列中准备运行。
    S (Sleeping): 进程正在睡眠状态,等待某些条件发生,比如等待输入/输出完成或接收信号。
    STAT列显示进程状态。
    T (Stopped): 进程由于收到作业控制信号而停止。
    t (Tracing): 进程正在被跟踪或调试。
    X (Dead): 已经死亡的进程。
    Z (Zombie): 僵尸进程,进程已经终止,但父进程还未收割它。

    < (高优先级): 该进程的优先级较高,不太友好地占用了更多资源。
    N (低优先级): 该进程的优先级较低,对其他用户更加友好。
    L (锁定页面): 该进程的部分页面被锁定在内存中,通常用于实时应用程序和自定义IO操作。
    s (会话领导者): 该进程是一个会话的领导进程。
    l (多线程): 该进程是一个多线程进程,使用了CLONE_THREAD标志,如NPTL pthreads所做的那样。
    + (前台进程组): 该进程属于前台进程组,可以接收来自终端的输入。


ps -ef: Unix风格，显示ppid、C(进程的CPU占用率)

ps axjf: 显示进程之间的关系
PPID - 父进程ID
PID - 进程ID
PGID - 进程组ID
SID - 会话ID
TTY - 进程关联的终端
TPGID - 前台进程组ID, 对于有控制终端的前台进程,TPGID等于PGID(进程组ID); 对于没有控制终端的进程,比如大多数守护进程、内核线程等,TPGID显示为-1
STAT - 进程状态码
UID - 进程所有者的用户ID
TIME - CPU时间
COMMAND - 命令名称和参数

ps -eo pid,ppid,pgrp,sid,tty,stat,comm,cmd: 显示进程所属的进程组和会话组

ps -o pid,psr,cmd: 显示进程在哪个处理器上运行

更多和进程相关的命令:
    pidof  基于进程名来查找进程ID
    pgrep -l -a  基于进程名、用户名、进程ID等来查找进程ID
    kill [-signal] PID...  给进程发送信号，默认发送TERM信号
        冷知识: top 和 less 会响应WINCH信号,按照新窗口的尺寸,刷新显示的内容
    killall [-u user] [-signal] name...  给匹配程序名或用户名的多个进程发送信号
    pstree  输出一个树型结构的进程列表
EOF

echo -e '\033[0m'
