#!/usr/bin/env bash

echo -e '\033[38;2;102;153;204;1m'

cat << 'EOF'
shell 脚本是由 Shell 内部命令、能在命令行上运行的命令、控制语句及注释(以#开始的行)构成的纯文本文件，
以.sh 作为文件后缀名，能够被 Shell 程序解释执行。

脚本的第一行#!/bin/bash是shebag:  它指示使用什么解释器来运行脚本。
如果第一行没有给出shebang，则脚本被当前的shell解释。脚本可以由 shell 外的解释器（如 Python）运行。
运行脚本时，将启动新的解释器实例，并将脚本作为参数传给解释器实例，不会在当前shell中执行。


command1 && command2: command1执行成功后，才会执行command2
command1 || command2: 如果command1执行失败，则执行command2
例如, DEBUG=true; $DEBUG && Something happening

在 Shell 中,通配符(wildcards)用于匹配文件名或目录名
通配符只在未被引用时才会生效。如果将通配符放在单引号或双引号中,它们将被视为普通字符
常见的通配符及其用法:
* (星号)
  - 匹配任意长度(包括0个)的任意字符
  - 例如: *.txt 匹配所有扩展名为 .txt 的文件
? (问号)
  - 匹配任意单个字符
  - 例如: file?.txt 匹配 file1.txt、file2.txt 等
[ ] (方括号)
  - 匹配方括号内的任意一个字符
  - 例如: file[12].txt 匹配 file1.txt 和 file2.txt
  - 可以使用连字符 (-) 表示范围,如 [a-z] 匹配任意小写字母
  - 也可以使用感叹号 (!) 表示否定,如 [!0-9] 匹配任意非数字字符


例子: 根据用户输入的 y、yes、n 或 no 执行不同的命令
case $var in
    [yY] | [yY][eE][sS])
    command...
    ;;
    [nN] | [nN][oO])
    command...
    ;;
    *)
    ;;
esac

{ } (大括号)
  - 匹配大括号内的任意一个字符串
  - 例如: file{1,2}.txt 匹配 file1.txt 和 file2.txt
  - 也可以使用范围表示法,如 file{1..5}.txt 匹配 file1.txt 到 file5.txt
  - 例如: 创建一系列文件夹 mkdir {2007..2009}-0{1..9} {2007..2009}-{10..12}
~ (波浪号)
  - 仅在某些 Shell 中有效,用于匹配用户的主目录
  - ~user_name会展开成指定用户的家目录名, ~会展开为当前用户的家目录


在 Shell 程序中可以定义变量, 如 A=2023, 赋值号两边不能有空格
通过 unset 命令删除变量，通过 set 内建命令查看所有的变量
除了函数中的local变量外，shell中的变量均为全局变量。
变量名大小写敏感，必须以字母或下划线开头，后续可以包含数字、字母、下划线
被 readonly 修饰的变量为只读变量，不能被修改和 unset, 如readonly A=2021
变量引用时可以使用 $变量名 或 ${变量名}，后者可以避免歧义

上述变量只能在创建它们的 shell 脚本中使用，而环境变量(即全局变量)可以在 Shell 中的所有用户进程中使用
你可以用printenv、printenv key 命令来查看所有/指定的环境变量
定义环境变量 A: A=2023; export A 或 export A=2023
常用内置变量: $USER, $UID, $HOME, $PWD, $PATH,  $SHELL, $RANDOM


Shell将变量视为字符串而不是数字。Shell不支持浮点数运算。
Shell 支持以下整数运算:
 ** 幂运算，% 取余数
 +, -, *, / 基本算术运算
 <<, >> 按位左移、右移
 &, ^, | 按位与、异或、或
 &&, || 逻辑与、或
 <, >, ==, !=, <=, >= 比较运算
 =, +=, -=, *=, /=, <<=, >>=, &=, ^=, |= 赋值运算

Shell中不能直接进行算术运算, 如x=1; $x=$x+1会报错: command not found: 1=1+1
执行算术运算时，要用 $((operation)) 语法, 算术运算符两边可以有空格
例如, x=$((3 + 5));$(($x + 1)); $((x=2 ** 10))
不加 $ 的 ((operation)) 是一条独立的语句，不能被其他表达式使用:
如: ((x=x+1+2)); $x是可以的, ((x=x+1+2))则会报错
let 命令也可以执行算术运算，而不需要使用 $((operation)) 语法:
例如, x=1;let x=x+3;$x
expr 是另一个能执行算术运算的外部程序:
expr 4 \* 5; x=$(expr 3 + 5); $x
最佳实践: $((...))用于执行算术运算并将结果赋值给变量, ((...)) 用于 if 语句或循环中
eval 命令将所有参数连接成一个单独的命令，然后在当前 shell 环境中执行该命令
例如, cmd=ls;arg=-La;eval $cmd $arg

| 输入格式                           | 说明                                     |
| ---------------------------------- | ---------------------------------------- |
| read                               | 从标准输入读取一行,赋值给内置变量 REPLY  |
| read var                           | 从标准输入读取一行,赋值给变量 var        |
| read -a arr                        | 从标准输入读取一行,赋值给数组 arr        |
| read -p please input your name     | 打印一个提示符                           |
| read -t                            | 设置一个超时时间                         |
| 输出格式                           | 说明                                     |
| echo -n string                     | 输出 string 后,不会输出换行符            |
| echo -e "\t"                       | 将\t解析为制表符                         |

引号的区别
不被引号包裹的字符串,会进行单词分割和通配符扩展。例如，*.c会被扩展为a.c b.c c.c
单引号:忽略所有特殊字符,原样输出
双引号:忽略大部分特殊字符,但不忽略以下特殊字符:
   $: 用于引用变量
   : 用于命令替换
  \: 用于转义字符, 如 echo "The balance for user $USER is: $5.00"
反引号: 用于命令替换,等同于$(cmd).
  $(cmd)示例: $(basename $(pwd))
  不同于$(cd /tmp; ls), (cd /tmp; ls)是在子shell中切换目录并执行命令

建议始终将变量用双引号包裹起来.否则,
foo bar将被视为两个独立的参数 foo 和 bar;
如果参数包含通配符 *,Shell 会将其扩展为匹配的文件名。


字符串操作:
 \t 字符下标的取值从0到${#str} - 1
 \t pattern,old中可以使用通配符
| 操作             | 说明                                      |
| -----------------| ------------------------------------------|
| ${#str}         | 返回字符串的长度                           |
| ${str:m}        | 返回从第m个字符到最后的子串(m的值从开始)   |
| ${str:m:len}    | 返回从第m个字符开始,长度为len的子串        |
| ${str#pattern}  | 删除字符串开头与pattern匹配的最小部分      |
| ${str##pattern} | 删除字符串开头与pattern匹配的最大部分      |
| ${str%pattern}  | 删除str结尾与pattern匹配的最小部分         |
| ${str%%pattern} | 删除str结尾与pattern匹配的最大部分         |
| ${str/old/new}  | 用new替换字符串中第一次出现的old           |
| ${str//old/new} | 用new替换字符串中的所有old                 |


括号的区别
| 带括号的表达式 | 说明                                     |
| -------------- | --------------------------------------   |
| ${...}         | 引用变量                                   |
| $(cmd)         | 命令替换,将 cmd 命令的输出结果替换到该位置|
| $[...]         | 执行算术运算，结果可以赋值给另一个变量    |
| $((...))       | 同上                                      |
| ((...))        | 算术运算                                  |
| [...]          | 条件测试                                  |
| [[...]]        | 现代的条件测试，支持模式匹配、正则表达式等 |


命令行参数 (通过命令行向脚本传递用空格分开的字符串参数)
在脚本中通过位置引用这些参数,$1表示第一个参数,${10}表示第 10 个参数。
| 位置参数 | 作用                                                         |
| -------- | ------------------------------------------------------------ |
| $0     | 脚本文件名                                                   |
| $#     | 传递给脚本的参数总数,不包括$0                             |
| $$     | 脚本进程号                                                   |
| $!     | 最后一个后台进程的进程号                                     |
| $?     | 上一条脚本或命令的退出码,值是0到255之间的整数, 0表示成功退出,否则异常退出|
| $*     | 传递给脚本的所有参数,作为单个字符串                         |
| $@     | 传递给脚本的所有参数,作为单独的字符串(更常用,更安全)     |


创建数组: array1=(2023 apple banana orange)
修改数组元素: arr[0]=2021
访问数组元素: ${array[0]} ${array[@]}, arr[@] 比 arr[*] 更加健壮和可靠
获取数组长度: ${#array[@]}
遍历数组: for item in ${array[@]}; do   $item done
用下标遍历数组: for index in ${!array[@]}; do   Index: $index, Value: ${array[$index]} done
排序: arr=(3 1 4 2 5) sorted_arr=($(echo '${arr[@]}' | tr ' ' '\n' | sort))
追加元素: array+=(grape apple)
删除元素: unset array[2]
注意，与其它语言中的动态数组不同，删除shell数组中的元素后，会留下空洞。
连接数组: combined=(${array1[@]} ${array2[@]})

代码示例:
# 初始化数组
arr=(apple banana cherry date elderberry)

echo "${arr[@]}" # apple banana cherry date elderberry

unset 'arr[2]' # 删除 cherry

echo "${arr[@]}" # apple banana date elderberry

echo "数组长度：${#arr[@]}" # 数组长度：4

# 遍历并打印数组索引和值
for i in "${!arr[@]}"; do
  echo "索引 $i: ${arr[$i]}"
done
# 索引 0: apple
# 索引 1: banana
# 索引 3: date
# 索引 4: elderberry


定义关联数组: declare -A person
赋值: person=([name]=John Doe [age]=30 [city]=New York)
访问: ${person[name]}
修改: person[age]=35
遍历: for key in ${!person[@]}; do $key: ${person[$key]} done


评估一个条件表达式是否为真:
[[ condition ]] 或 test condition
条件表达式的两侧必须有空格, 否则Shell 会将其解释为一个命令或函数名
如果条件测试为真, 返回退出码0, 否则返回1
内置命令true返回0, false返回1
使用exit关键字来指定脚本的退出码。如果脚本省略了exit 语句，则退出码为上次执行命令的退出码


字符串测试,
| 字符串测试(运算符两侧必须有空格)| 说明                     |
| --------------------------| ------------------------ |
| [[ -z $str ]]             | 字符串长度为0,返回真     |
| [[ -n $str ]]             | 字符串不为空,返回真      |
| [[ $str1 == $str2 ]]      | 两字符串相等             |
| [[ $str1 != $str2 ]]      | 两字符串不等             |

整数测试
((int1 > int2))  ((x == 1))
下面是另一种写法，更繁琐
| --------------------- | ------------------------ |
| [[ $int1 -eq $int2 ]] | int1等于int2             |
| [[ $int1 -ne $int2 ]] | int1不等于int2           |
| [[ $int1 -gt $int2 ]] | int1大于int2             |
| [[ $int1 -lt $int2 ]] | int1小于int2             |
| [[ $int1 -ge $int2 ]] | int1大于等于int2         |
| [[ $int1 -le $int2 ]] | int1小于等于int2         |


逻辑测试
[[ $exp1 && $exp2 ]]  [[ $exp1 || $exp2 ]] [[ ! $exp ]]
下面是另一种写法
[[ exp1 -a exp2 ]] [[ exp1 -o exp2 ]] [[ !exp ]]


| 文件测试      | 满足下列条件,则返回真   (man test)
| 文件测试     | 说明                                  |
| ------------ | ------------------------------------- |
| -f filename  | 普通文件存在                          |
| -d filename  | 目录文件存在                          |
| -e filename  | 文件或目录存在                        |
| -L filename  | 链接文件存在                          |
| -s filename  | 文件非空, s是size的缩写               |
| -r filename  | 文件或目录可读                        |
| -w filename  | 文件或目录可写                        |
| -x filename  | 文件或目录可执行                      |

trap命令用于为信号(signal)注册一个命令(command)
当 shell 脚本接收到指定的信号时，将执行注册的命令
trap pid $$ received sigint or sigquit!; exit 0 2 3
cleanup() {...} trap cleanup EXIT
常见的信号包括: 1(HUP) 2(INT) 3(QUIT) 6(ABRT) 14(ALRM) 15(TERM)


if语句用于根据条件执行不同的代码块。其基本格式如下：
if [ condition ]; then
    # 在条件满足时执行的代码块
else
    # 在条件不满足时执行的代码块
fi
condition可以为多条命令, 以最后一个命令的退出状态为条件值
代码块可以为:表示的空命令
例如：
if ((x == 10)); then
    x is 10
else
    x is not 10
fi


case语句用于根据不同的模式匹配执行不同的代码块。其基本格式如下：
case $variable in
    pattern1)
        # 匹配模式1时执行的代码块
        ;;
    pattern2)
        # 匹配模式2时执行的代码块
        ;;
    *)
        # 默认情况下执行的代码块
        ;;
esac # esac是case倒着写
例如：
case $fruit in
    apple)
        \Its an apple\
        ;;
    banana|orange)
        \Its a banana or an orange\
        ;;
    *)
        \Its something else\
        ;;
esac


for语句用于循环执行一系列命令。其基本格式如下：
for variable in list
do
    # 在每个list中的元素上执行的命令
done
例如：
for fruit in apple banana orange
do
    I like $fruit
done
for语句还可以使用 C 风格的循环，其格式如下：
for ((exp1;exp2;exp3))
do
    # 在每次迭代中执行的命令
done
例如打印三角形：
for ((i=0;i<9;++i))
do
    for ((j=0;j<$((9 - i - 1));++j))
    do
        -n
    done
    for ((j=0;j<$((2 * i + 1));++j))
    do
        -n *
    done
    -ne \\n
done


while语句用于根据条件循环执行一系列命令。其基本格式如下：
while condition
do
    # 在条件满足时执行的命令
done
例如：
while [[ $1 !=  ]]
do
    $1
    shift
done


until语句与while语句类似，不同之处在于它在条件为假时执行循环。其基本格式如下：
until condition
do
    # 在条件不满足时执行的命令
done
例如：
count=0
until ((count == 3))
do
    $count
    ((count++))
done


break和continue用于控制循环的执行流程。
break 用于跳出当前循环，终止循环的执行。
continue 用于跳过当前循环中的剩余命令，直接进行下一次循环迭代。
可以在 break 或 continue 后面加上一个数字 n，表示跳出或跳过第 n 层循环。


select 是一个内置命令,用于创建交互式菜单,让用户从列表中选择一个或多个选项
用法如下:
PS3=请选择一个选项:   # 设置提示符
options=(Option 1 Option 2 Option 3 Quit)
select opt in ${options[@]}
do
    case $opt in
        Option 1)
            你选择了 Option 1
            ;;
        Option 2)
            你选择了 Option 2
            ;;
        Option 3)
            你选择了 Option 3
            ;;
        Quit)
            break
            ;;
        *)
            无效选项
            ;;
    esac
done


函数的基本语法:
函数中不带local关键字的变量是全局变量,它们可以在函数外部引用
使用return关键字为函数指定退出码, 否则退出码是上次执行命令的退出码
[function] function_name()
{
    command1
    command2
    ...
}
例如:
func()
{
    函数参数个数为:$#
    第一个参数为$1
    第二个参数为$2
}
调用函数: func hello world


某脚本调用其它脚本中的函数时，需要先将被调用脚本加载到当前环境中:
. ./functions.sh 或 source ./functions.sh


IO重定向:
 输出重定向
   command > file: 将命令的标准输出重定向到文件中,覆盖文件原有内容。
   command >> file: 将命令的标准输出重定向到文件中,追加到文件末尾。
 输入重定向
   command < file: 将文件的内容作为命令的标准输入。
 错误重定向
   command 2> file: 将命令的标准错误输出重定向到文件中,覆盖文件原有内容。
   command 2>> file: 将命令的标准错误输出重定向到文件中,追加到文件末尾。
 重定向到文件描述符
   command <&3: 将文件描述符 3 作为命令的标准输入。
   command >&4: 将文件描述符 4 作为命令的标准输出。
   < 和 &3 之间是不能加空格的。这是因为 & 符号用于指示后面的数字是一个文件描述符，而空格会打断这种语法结构。
 合并输出和错误
   command > file 2>&1: 将命令的标准输出和标准错误输出都重定向到同一个文件中。
   command &> file: 这是上一条命令的简写形式。
 丢弃输出或错误
   command > /dev/null: 将命令的标准输出丢弃。
   command 2> /dev/null: 将命令的标准错误输出丢弃。
   command &> /dev/null: 将命令的标准输出和标准错误输出都丢弃。
 Here 文档
   - command << TOKEN: 将后续行作为命令的标准输入,直到遇到 TOKEN 为止。
   - command << 'TOKEN': 所有字符都会被当作纯文本,不会进行任何解释和替换。
 tee命令
     tee表示管道系统中T形连接件
     从标准输入读取数据, 输出到标准输出, 同时也将数据写入到一个或多个文件中。

后台作业:
&
将命令放入后台运行。例如，some_command & 将启动 some_command 并立即返回提示符。

jobs
列出当前会话中的所有作业及其状态。作业编号前面带有百分号（%）。

fg
将后台作业带到前台继续运行。使用 fg %n 可以将作业编号为n的作业带到前台。

bg
使一个暂停的作业在后台继续运行。使用 bg %n 可以将作业编号为n的作业继续在后台运行。

Ctrl+Z
暂停当前正在运行的前台作业，并将其放入后台（作为停止状态）。

kill
发送信号给作业。使用 kill %n 可以发送信号给作业编号为n的作业，默认信号为TERM，终止作业。
也可以发送其他信号，如 kill -9 %n 强制终止作业。

disown
从当前会话的作业列表中移除作业，使得作业在当前shell退出后继续运行。
使用 disown %n 可以移除作业编号为n的作业。


调试:
set -x (xtrace) 在执行每个命令之前,打印出该命令及其参数、扩展后的通配符
set -v (verbose) 在执行每个命令之前,打印出该命令行
set +x 关闭set -x
set -euo pipefail, 即set -e; set -u; set -o pipefail
它们的全称是exit, unset, pipfail:
  任何命令的返回码不是 0(成功),则立即退出;
  使用未定义的变量,则报错并退出;
  管道中任何一个命令返回非零退出码,则整个管道命令将返回非零退出码

EOF

echo -e '\033[0m'
