#!/usr/bin/env bash

echo -e '\033[38;2;102;153;204;1m'

cat << EOF
systemctl status dhcpcd         # 查看服务状态

systemctl enable dhcpcd         # 设置开机启动服务
systemctl enable --now dhcpcd   # 设置服务为开机启动并立即启动
systemctl disable dhcpcd        # 取消开机自动启动

systemctl start dhcpcd          # 启动服务
systemctl stop dhcpcd           # 停止服务

systemctl restart dhcpcd        # 重启服务
systemctl reload dhcpcd         # 重新加载配置文件
systemctl daemon-reload dhcpcd  # 重新加载修改后的配置文件
EOF

echo -e '\033[0m'
