#!/usr/bin/env bash

echo -e '\033[38;2;102;153;204;1m'

cat << EOF

general regular expression parser, 使用正则表达式查找文件中的模式。
grep [选项] [模式(用单引号包裹)] [文件...]

常用的 grep 命令参数:
-i                  忽略大小写匹配。
-v                  反转匹配，选择不匹配的行。
-c                  计数匹配行的数量。
-n                  显示匹配行及其行号。
-l                  仅显示包含匹配的文件名。
-L                  仅显示不包含匹配的文件名。
-r 或 -R            递归搜索目录。
-w                  仅匹配整个单词。
-x                  仅匹配整行。
-a,                 将所有输入文件当作文本文件处理，即使它们包含二进制数据。
-q                  静默模式，不输出任何匹配行。找到/未找到匹配的文本时，退出状态为0/1。
-E                  使用扩展正则表达式。
-F                  将模式作为固定字符串处理，不解释任何正则表达式。
-A [行数]            打印匹配行和之后的指定行数。
-B [行数]            打印匹配行和之前的指定行数。
-C [行数]            打印匹配行的前后指定行数。
--color=auto        匹配文本着色显示。

示例用法:
在文件 'file.txt' 中搜索 空行：
grep '^$' file.txt

不显示配置文件的注释行:
grep -v '^#' conf

在当前目录及子目录中搜索包含 'pattern' 的文件：
grep -r 'pattern' .

在文件 'file.txt' 中忽略大小写地搜索 'pattern'：
grep -i 'pattern' file.txt

计算文件 'file.txt' 中 'pattern' 出现的次数：
grep -c 'pattern' file.txt

在文件 'file.txt' 中搜索 'pattern'，并显示行号：
grep -n 'pattern' file.txt

在多个文件中搜索 'pattern'，仅显示包含匹配的文件名：
grep -l 'pattern' file1.txt file2.txt

EOF

cat << EOF

常用的正则表达式元字符:

^        匹配行的开始。例如，'^grep' 匹配所有以 'grep' 开头的行.
$        匹配行的结束。例如，'grep$' 匹配所有以 'grep' 结尾的行.
.        匹配任意单个字符（除了换行符）.
*        匹配前一个字符零次或多次。例如，'gre*p' 匹配 'gp'、'grep'、'greeep' 等.
[]       匹配括号内的任意字符集合。例如，'gr[ae]p' 匹配 'grep' 或 'grap'.
[^]      匹配不在括号内的任意字符集合。例如，'gr[^ae]p' 匹配 'grxp' 但不匹配 'grep' 或 'grap'.
\<       匹配单词的开始。例如，'\<grep' 匹配所有以 'grep' 作为独立单词开始的行.
\>       匹配单词的末尾。例如，'grep\>' 匹配所有以 'grep' 作为独立单词结束的行.
[a-b]    匹配a到b之间的任意单个字符（包括a和b）.
\        转义字符，用于匹配特殊字符。例如，'\.' 会匹配实际的点字符.

扩展正则表达式元字符（使用 'grep -E' 或 'egrep'）:

+        匹配前一个字符一次或多次。例如，'gre+p' 匹配 'grep'、'greeep' 但不匹配 'gp'.
?        匹配前一个字符零次或一次。例如，'gre?p' 匹配 'gp' 或 'grep' 但不匹配 'greeep'.
|        逻辑或操作。例如，'grep|egrep' 匹配 'grep' 或 'egrep'.
()       分组。例如，'(gr|e)rep' 匹配 'grep' 或 'erep'.
{}       匹配前一个字符的指定次数。例如，'gre{2}p' 匹配 'greeep' 但不匹配 'grep'.
{j,}     匹配前一个字符至少j次.
{,k}     匹配前一个字符最多k次.
{j,k}    匹配前一个字符至少j次，但不超过k次.
\b       单词边界。例如，'\bgrep\b' 匹配 'grep' 但不匹配 'egrep'.

EOF

echo -e '\033[0m'
