#!/usr/bin/env bash

echo -e "sed(stream editor) 是一个非交互式的（非所见即所得）流式编辑器"
echo -e "-sed 逐行读取文件内容（不会修改源文件的内容，可加上-i参数以原地修改）"
echo -e "存储在称为 pattern space 的临时缓冲区中，处理缓冲区中的内容并将结果打印到屏幕"
echo -e 'sed常用于在命令行中进行查找和替换操作'
echo
echo -e "sed [选项]... {sed 脚本} [输入文件]..."
echo
echo "sed脚本由单引号包裹,可以指定被编辑的行和要进行的操作。"
echo
echo "执行多条sed编辑命令："
echo "- 用分号分隔sed编辑命令   sed 's/a/A/;s/b/B/' test"
echo "- sed编辑命令前添加-e选项    sed -e 's/a/A/' -e 's/e/E/' test"
echo "- 在sed后输入单引号,输入换行符,启用多行编辑命令   sed ' "
echo "s/a/A/"
echo "s/e/E/' test"
echo
echo "从文件读取sed脚本: 用-f选项指定存放sed脚本的文件, 如sed -f test.sed test"
echo
echo ""
echo "| 指定行的方式          | 说明                           |"
echo "| --------------------- | ------------------------------ |"
echo "| m                     | 第m行                          |"
echo "| m,n                   | 从m行到n行                     |"
echo '| $                     | 最后一行                       |'
echo "| /pattern/             | 包含指定模式的行               |"
echo "| /pattern/,m           | 从包含指定模式的行到第m行      |"
echo "| m,/pattern/           | 从第m行到包含指定模式的行      |"
echo "| /pattern1/,/pattern2/ | 从包含模式1的行到包含模式2的行 |"
echo "| !                     | 反向选择                       |"
echo ""
echo "| 操作 | 说明                                                         |"
echo "| ---- | ------------------------------------------------------------ |"
echo "| p    | 打印匹配行                                                   |"
echo "| l    | 打印匹配行,并显示控制字符                                   |"
echo "| =    | 显示匹配行的行号                                             |"
echo "| d    | 删除匹配行                                                   |"
echo '| a\   | 在指定行后追加行                                             |'
echo '| i\   | 在指定行前插入行                                             |'
echo '| c\   | 用新行替换指定行                                             |'
echo "| s    | 替换命令。 s/old/new/[gpw],g为全部替换,p为打印替换后的行,w将替换后的行写入指定文件 |"
echo "| r    | 读文件。sed '\$r test2' test将test2文件追加到test文件的末尾。 |"
echo "| w    | 写文件。sed '/a/w test2' test将test文件中包含a的行写入到test2中。 |"
echo "| n    | 将指定行的下一行读入缓冲区。sed '/hello/{n;s/a/A/}' test 将 含有hello行的下一行,中的第一个a替换为A |"

echo "+----------------------------------+------------------------------------------------+"
echo "| sed示例                          | 说明                                           |"
echo "+----------------------------------+------------------------------------------------+"
echo "| sed '/^$/d'                | 删除空行 |"
echo "| sed '4,\$d' test                | 删除test文件的第四行到最后一行,即只输出前三行 |"
echo "| sed '3/foo/d' test                | 删除第3行,如果它包含 foo |"
echo "| sed '3q' test                  | 处理完第三行时退出                             |"
echo "| sed 's/a/A/' test              | 将每行的第一个a替换为A                         |"
echo "| sed 's/a/A/i' test              | 不考虑大小写                         |"
echo "| sed 's/a/A/2' test              | 只替换第二次出现的内容                         |"
echo "| sed 's/a/A/g' test             | 将每行的所有a替换为A                           |"
echo "| sed 's/a/A/gw test2' test      | 将替换后的行输出到test2文件中                  |"
echo "| sed -n 's/a/A/p' test          | 只输出含有a的行,且将每行的第一个a替换为A      |"
echo "| sed  -n '3,6p' test            | 打印第三行到第六行                             |"
echo "| sed -n '3,6!p' test            | 打印除了第三行到第六行外的行                   |"
echo "| sed  '/e/a\EEE' test           | 在包含e的行后追加EEE行                         |"
echo "| sed 's/[0-9][0-9]\$/&.0/' test  | 将连续的两位数后面加上.0                       |"
echo "+----------------------------------+------------------------------------------------+"
