#!/usr/bin/env bash

cat << 'EOF'

$(echo -e '\033[38;2;255;255;0;1m')
'su' 适合于临时切换用户权限, 你将获得目标用户的权限,但继续使用原始用户的HOME目录、PATH设置等。

'su -' (是su --login root的简写) 适合于需要完全模拟用户登录会话的情况。
- 或 -l 选项启动一个login shell, 这会加载此用户的 shell 环境, 并且工作目录会更改到这个用户的家目录。
这通常用于切换到root用户,因为它提供了一个干净的环境,避免了权限和环境变量冲突的问题。

/etc/sudoers文件定义了哪些用户可以使用sudo命令以及可以执行哪些命令,通常由系统管理员使用visudo命令进行编辑。
sudo 命令允许一个普通用户以root用户的身份来执行命令, 使用 sudo 命令时,用户使用他自己的密码来认证, 而不是管理员密码。
sudo 不会重新启动一个 shell,也不会加载另一个用户的 shell 运行环境。

$(echo -e '\033[38;2;102;153;204;1m')
who - 显示当前登录系统的所有用户信息
who am i - 显示当前用户会话的信息(比whoami显示更多的信息)
whoami - 打印当前有效用户的用户名

id [选项] [用户] - 打印当前用户或指定用户的用户ID、主组ID、所有组的ID
groups [用户] - 显示当前用户或指定用户所属的所有组

$(echo -e '\033[38;2;255;102;0;1m')
useradd [选项] 用户名 - 创建新用户
   常用选项:
     -m, --create-home     创建用户主目录
     -G, --groups          指定用户所属的附加组
     -s, --shell           指定用户的登录shell

usermod [选项] 用户名 - 修改用户账户
   常用选项:
     -l, --login           修改用户名
     -g, --gid             修改用户主组
     -G, --groups          修改用户所属的附加组
     -s, --shell           修改用户的登录shell

userdel [选项] 用户名 - 删除用户账户
     -r, --remove          删除用户主目录和邮件副本

$(echo -e '\033[38;2;102;153;204;1m')
groupadd [选项] 组名 - 创建新组
    常用选项:
      groupadd groupname - 创建一个新的用户组
      groupadd -g GID groupname - 创建一个新的用户组并指定GID
      groupadd -r groupname 创建一个新的系统组

groupmod [选项] 组名 - 修改组
    常用选项:
      -n new_groupname old_groupname       更改组名
      -g new_GID groupname       更改组的GID

groupdel 组名 - 删除组

newgrp groupname - 切换当前用户的活动组(用户必须是目标组的成员)

$(echo -e '\033[38;2;255;102;0;1m')
管理用户和用户组的配置文件为: /etc/passwd /etc/shadow /etc/group /etc/gshadow
出于安全考虑,/etc/passwd文件中只保存了用户信息,包括用户名、密码占位符、UID、GID、注释、用户主目录、用户Shell等(man 5 passwd)
真正的密码保存在/etc/shadow文件中(man 5 shadow)

$(echo -e '\033[38;2;255;0;255;1m')
passwd [选项] [用户] - 修改用户密码
    常用选项:
      -d, --delete           删除用户密码
      -l, --lock           锁定用户密码,禁止用户登录
      -u, --unlock         解锁用户密码,允许用户登录

gpasswd - 修改组成员和密码
    gpasswd -a user group - 向组中添加用户
    gpasswd -d user group - 从组中删除用户
    gpasswd -A user group 设置组管理员
    gpasswd group - 创建或更新组密码
    gpasswd -r group - 删除组密码

chage [选项] 用户名 - 修改用户密码过期信息
    常用选项:
      -l, --list           列出用户的密码过期信息
      -d, --lastday        设置最后一次密码更改日期
      -E, --expiredate     设置账户过期日期

chown命令用于更改文件或目录所有者。
chown [选项] [所有者][:组] 文件/目录
EOF

echo -e '\033[0m'
