#!/usr/bin/env bash

echo -e '\033[38;2;255;255;0;1m'

cat << 'EOF'

alt + z toggle wrap line
ctrl + shift + l 重命名函数或变量
ctrl + d 多次按，增量选择要重命名的函数或变量
ctrl + / 行注释
shift + alt + f 格式化
alt + 上下箭头 上下移动行
ctrl + p 打开最近的文件
ctrl + l 选择整行
ctrl + g 跳转到特定行
ctrl + k w 关闭所有选项卡

EOF

echo -e '\033[0m'
